#----------------------------------------------------
#Compilation Options. Possible values [T | F]
#  [*] T: True and F: False
#----------------------------------------------------
OPENBLAS_ENABLE = F
BLIS_ENABLE     = F
OMP_ENABLE      = T
#----------------------------------------------------


#----------------------------------------------------
#Path Libraries. Only necessary if it is enabled
#----------------------------------------------------
OPENBLAS_HOME   = ./src/OpenBLAS/install/
BLIS_HOME       = ./src/blis/install/
#----------------------------------------------------

